# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84064f97f837c164b5107e3298550688c9b947fc15e2a0d6f9e686a98f50153dc8ddca54498507d5ee12a980bbf09eaf8372bc30a033bbedf52e330ed637f845

test:
  secret_key_base: 1af92e65c8bb2470cbd1b7bf251cfd42b40a0aed88069a55d29a7212ba49bc5d193c5e11859da05e5bf0c6921b259fd1735196cbe4e67bba6abe5b918822b4b9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
